# Generated by Django 4.1.7 on 2023-04-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Категория')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/categorys/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Категории',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название цвета')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/products/', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название размера')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Цена')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('main_image', models.ImageField(upload_to='images/products/', verbose_name='Основная фотография')),
                ('categorys', models.ManyToManyField(to='store.category')),
                ('other_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.imagesproduct')),
            ],
            options={
                'verbose_name': 'Продукты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество продукта')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid', to='store.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid', to='store.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid', to='store.size')),
            ],
        ),
    ]
