# Generated by Django 4.1.7 on 2023-03-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorys',
            field=models.ManyToManyField(related_name='products', to='store.category'),
        ),
    ]
