# Generated by Django 4.1.7 on 2023-03-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorys',
            field=models.ManyToManyField(related_name='products', related_query_name='products', to='store.category'),
        ),
    ]
