# Generated by Django 4.1.7 on 2023-03-12 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorys',
            field=models.ManyToManyField(to='store.category'),
        ),
    ]
