# Generated by Django 4.1.7 on 2023-03-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_category_products_alter_product_categorys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
    ]
