# Generated by Django 4.1.7 on 2023-03-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_category_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Категории'},
        ),
    ]
