# Generated by Django 4.1.7 on 2023-03-12 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Продукты'},
        ),
    ]
