# Generated by Django 4.1.7 on 2023-03-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_0',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/products/', verbose_name='Фотография'),
        ),
    ]
