# Generated by Django 4.1.7 on 2023-03-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_image_0_product_image_1_product_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_0',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/products/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/products/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/products/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/products/', verbose_name='Фотография'),
        ),
    ]
