# Generated by Django 4.1.7 on 2023-03-13 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_color_size_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid', to='store.color'),
        ),
        migrations.AlterField(
            model_name='count',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid', to='store.size'),
        ),
    ]
