# Generated by Django 4.1.7 on 2023-03-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_count_color_alter_count_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count_stock',
        ),
    ]
