# Generated by Django 4.1.7 on 2023-03-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.AddField(
            model_name='productorder',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='color',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='size',
            field=models.CharField(max_length=16),
        ),
    ]
