# Generated by Django 4.1.7 on 2023-03-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_productorder_product_productorder_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.CharField(default=1, max_length=666),
            preserve_default=False,
        ),
    ]
