# Generated by Django 4.1.7 on 2023-03-20 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_count_stock'),
        ('cart', '0003_remove_productorder_product_id_productorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
