# Generated by Django 4.1.7 on 2023-04-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_order_products_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.JSONField(default=None, verbose_name='Продукты'),
        ),
    ]
