name: Ecommerce Django Project

on:
  push:
   branches: [ docker ]
  pull_request:
    branches: [ docker ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "lilchiken" --password-stdin
        docker image build -t lilchiken/ecommerce-django-project:latest .
        docker push lilchiken/ecommerce-django-project:latest